version: 0.2

phases:
  pre_build:
    commands:
      - echo update npm
      - sudo npm update npm
      - echo update node
      - sudo npm update node
      - echo Installing dependencies
      - npm install
  build:
    commands:
      - echo Building app
      - npm run build
  post_build:
    commands:
      - echo Copying public files to S3 hosting
      - aws s3 cp --recursive ./dist/ s3://www.carlosregaladodev.com