version: 0.2

phases:
  pre_build:
    commands:
      - echo Install latest npm version
      - sudo npm i -g npm@latest
      - echo Installing dependencies
      - npm install
      - echo Install sass
      - npm install sass --save-dev
  build:
    commands:
      - echo Building app
      - npm run build
  post_build:
    commands:
      - echo Copying project files to S3 hosting
      - aws s3 cp --recursive ./dist s3://www.carlosregaladodev.com