version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing dependencies
      - npm install
  build:
    commands:
      - echo Building app
      - npm run build
  post_build:
    commands:
      - echo Copying public files to S3 hosting
      - aws s3 cp --recursive ./public/assets s3://www.carlosregaladodev.com/assets/
      - aws s3 cp --recursive ./public/css s3://www.carlosregaladodev.com/css/
      - aws s3 cp --recursive ./src/assets/script s3://www.carlosregaladodev.com/assets/
      - aws s3 cp index.html s3://www.carlosregaladodev.com